Development
keshav-c/smashing-mag pull request #1
Opened 2019-05-15 16:49 UTC by keshav-c

Awaiting your comments. We haven't done much for the header and footer sections as per the project requirements.

We have created 2 pages, one representing the original and the other it's grey-scale heatmap as per our perception.

Both are linked together via hyper links in the header.

2019-05-18 20:21 UTC, efrapp requested changes
# Good Job! but I want you to address some things

The purpose of this project is to enforce design principles so you made a great job creating the grayscale heat map page and also the other page was great but is not needed for this project, you don't need to delete it it is just to put the focus in the grayscale page because there you are applying the key concepts for this project.

The things I want you to address are the followings:

1. Apply the correction shown in the HTML validator [here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkeshav-c.github.io%2Fsmashing-mag%2Findex.html). This is for the `index.html` file but it is important that you have those corrections in mind.
2. Apply the corrections shown in the HTML validator for the [`heatmap.html`](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkeshav-c.github.io%2Fsmashing-mag%2Fheatmap.html) file.
3. Please update your GitHub Page link because in the CSS validator it shows errors that you already solved. See [here](http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fkeshav-c.github.io%2Fsmashing-mag%2Fstyles%2Fmain.css).

For point 1 and 2 pay more attention to the errors than the warnings.

When you are done with this changes, please, submit a new code review to check the changes.

2019-05-18 20:21 UTC, efrapp commented on styles/main.css
> +    grid-template-columns: repeat(2, 1fr);
Don't worry about this error, it is something related to the [css lint](http://csslint.net/) Stickler uses. You can check a discussion about that here: https://github.com/CSSLint/parser-lib/issues/228

2019-05-18 20:21 UTC, efrapp commented on styles/main.css
> +    grid-template-rows: 5fr 4fr;
Same thing here and in all parts where this error appears.

2019-05-20 02:10 UTC, keshav-c commented on styles/main.css
> +    grid-template-columns: repeat(2, 1fr);
Thanks. I guess w3 validators are going to be more useful from now on, if stickler can't even validate grid layouts.

2019-05-20 02:11 UTC, keshav-c commented
I have made all corrections as suggested. Awaiting your re-review.

2019-05-21 20:47 UTC, efrapp approved these changes
# Ok you made a great job! 👍 

You can continue in your path to achieving the mastery!

You can submit now your completion form for this project.

I whish you the best.

2019-05-22 05:56 UTC, merged